### ISSUE TITLE
`Re__Perl.Parse_error` validating string with `@regex`

### ISSUE THREAD

**Issue by Favo02** [Axot017/validator#15]
Hello, first of all thanks for the amazing library, I just found this on OCaml forum and it is perfect, in combination with yojson, to convert and validate json.

I am validating this record, using `@regex`:

```ocaml
type user = {
    username : string; [@regex "/^[a-zA-Z0-9_]{4,16}$/"]
    password : string; [@regex "/^(?=.*[A-Za-z])(?=.*[0-9])(?=.*[@$!%*#?&])[A-Za-z0-9@$!%*#?&]{8,20}$/"]
} [@@deriving yojson, validate]
```

but the validations fails with error `Re__Perl.Parse_error`. The problem seems to be related to the lookahead of the password regex, a simpler regex like `^[A-Za-z0-9@$!%*#?&]{8,20}$/` works.

Thanks again for your work!

**Comment by Axot017** [comment]
Hi! 

Thanks for creating this issue. I'm happy that you fount this library useful. 

I investigated your issue a little bit and you are right, its because look-ahead. `validate` under the hood uses [ocaml-re](https://github.com/ocaml/ocaml-re) for regex validation which is DFA-based regex implementation, so it does not support look-ahead/look-behind assertions. To be honest i wasn't aware of that when i was choosing this library. I will try to experiment with [pcre-ocaml](https://github.com/mmottl/pcre-ocaml) which seems to support look-ahead and look-behind. I'm sorry but unfortunately,your problem probably won't be solved quickly because I don't want to change dependencies without checking them thoroughly.

**Comment by Axot017** [comment]
Update: [pcre-ocaml](https://github.com/mmottl/pcre-ocaml) seems to be not maintained. I will try to find other alternatives, but i don't see many ocaml regex libraries, so its highly likely that `validate` will not support look-ahead and look-behind

**Comment by Favo02** [comment]
Thanks for your time investigating the issue!

I'm not really familiar with OCaml, so this could be a really stupid question, but why `Str.regexp` module doesn't do the job?

**Comment by Axot017** [comment]
`Str.regexp` is very limited. Here is full list of contructs supported in `Str`: 
```
   - [.     ] Matches any character except newline.
   - [*     ] (postfix) Matches the preceding expression zero, one or
              several times
   - [+     ] (postfix) Matches the preceding expression one or
              several times
   - [?     ] (postfix) Matches the preceding expression once or
              not at all
   - [[..]  ] Character set. Ranges are denoted with [-], as in [[a-z]].
              An initial [^], as in [[^0-9]], complements the set.
              To include a [\]] character in a set, make it the first
              character of the set. To include a [-] character in a set,
              make it the first or the last character of the set.
   - [^     ] Matches at beginning of line: either at the beginning of
              the matched string, or just after a '\n' character.
   - [$     ] Matches at end of line: either at the end of the matched
              string, or just before a '\n' character.
   - [\|    ] (infix) Alternative between two expressions.
   - [\(..\)] Grouping and naming of the enclosed expression.
   - [\1    ] The text matched by the first [\(...\)] expression
     ([\2] for the second expression, and so on up to [\9]).
   - [\b    ] Matches word boundaries.
   - [\     ] Quotes special characters.  The special characters
              are [$^\.*+?[]].
```
After some research i did't find any reasonable alternative to [ocaml-re](https://github.com/ocaml/ocaml-re) that will be maintained and will support look-ahead and look-behind. Also I have no time (and skill 😄 ) to implement new one, so I decided I will leave regex handling in `validate` as it is. I will only add appropriate information in README.md. Sorry that I was not able to help.

**Comment by Favo02** [comment]
Thanks for your help, I will let you know if I find any solution.

**Comment by Favo02** [comment]
_Update:_

I will try to use the newly added `@custom` validator, verifying that every part of the original regex with lookahead is satisfied, effectively splitting the original regex with lookahead into multiple simpler regexes.

Related question _(because I'm lazy and if there's a way to avoid custom validator I will take it)_:

Is there any way to check for multiple validators at the same time, something like

```ocaml
  type ciao = {
    rating : int; [@greather_than 0; @smaller_than 11]
    password : string; [@regex "[a-z]"; @regex "[A-Z]"; @regex "[0-9]"]
  } [@@deriving validate]
```

**Comment by Axot017** [comment]
To test `[@custom ...]` annotation you will need to wait a little bit because 1.1.0 is still not merged to opam repository: https://github.com/ocaml/opam-repository/pull/25151. 
About multiple validators, its currently possible to have multiple validators to one field
```ocaml
  type ciao = {
    rating : int; [@greather_than 0] [@smaller_than 11]
    ...
  } [@@deriving validate]
```
However if I remember correctly its not possible to have multiple the same annotations, for example multiple `[@regex]` annotations.
